version: "3.3"
services:
  db:
    image: janusgraph/janusgraph:0.2.3
    ports:
      - "8182:8182"
    volumes:
      - ../janusgraph-conf:/etc/opt/janusgraph:ro
      - ./db:/var/lib/janusgraph
    networks:
      - db-net

networks:
  db-net:

volumes:
  janusgraph-conf:
  db:
