{-# LANGUAGE OverloadedStrings #-}
-- |
-- Module: NetSpider.RPL
-- Description: NetSpider data model and utility for RPL networks
-- Maintainer: Toshio Ito <debug.ito@gmail.com>
--
-- This module defines NetSpider data model and utility for RPL
-- networks.
--
-- RPL ([IPv6 Routing Protocol for Low-Power and Lossy Networks, RFC 6550](https://tools.ietf.org/html/rfc6550))
-- is a routing protocol for small wireless devices. Each node
-- independently exchanges routing information with its neighbors over
-- low-power wireless channels. Using those information, the nodes
-- form one or more network topologies called DODAG
-- (Destination-Oriented Directed Asynclic Graph) in a distributed
-- manner.
--
-- The module "NetSpider.RPL.Local" defines NetSpider data model
-- specific for RPL. The 'FoundNodeLocal' type in that module
-- represents a neighbor table stored in a single node. The neighbor
-- table contains RPL-specific information such as \"rank\" of each
-- neighbor. You can input the 'FoundNodeLocal's to NetSpider database
-- to construct the whole network topology.
--
-- The module "NetSpider.RPL.SR" defines another NetSpider data model,
-- 'FoundNodeSR'. It represents an entry in the source routing (SR)
-- table. In the \"non-storing mode of operation\" of RPL, downward
-- routes are maintained in a centralized way at the DODAG root node,
-- while upward routes are maintained locally in every node. You can
-- use 'FoundNodeSR's to represent upward routes.
--
-- Because network topologies maintained in 'FoundNodeLocal' and
-- 'FoundNodeSR' can be different, you have to use different node IDs
-- for them. The module "NetSpider.RPL.FindingID" exports 'FindingID'
-- that distingushes those two types of topologies.
--
-- The module "NetSpider.RPL.ContikiNG" (not re-exported by this
-- module) is a utility module to make 'FoundNodeLocal's and
-- 'FoundNodeSR's. It defines utility functions to read and parse log
-- files generated by Contiki-NG applications.
-- [Contiki-NG](http://contiki-ng.org/) is a tiny operating system
-- for wireless devices that supports RPL.
module NetSpider.RPL
       ( module NetSpider.RPL.FindingID,
         module NetSpider.RPL.Local,
         module NetSpider.RPL.SR
       ) where

import NetSpider.RPL.FindingID
import NetSpider.RPL.Local
import NetSpider.RPL.SR

